version: '1.0'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO-INITDB_ROOT_USERNAME = admin
      - MONGO-INITDB_ROOT_PASSWORD = admin
